## Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as np

### Creating array from list

In [3]:
arr_1 = np.array([1,2,3,4,5,6])
print("1D array: ", arr_1)

arr_2 = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2)

1D array:  [1 2 3 4 5 6]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [6]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication: ", np_array * 2)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]


### creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 2))
print("random array: \n", random)

seq = np.arange(0,11, 2)
print("Sequence array: \n", seq)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.88817915 0.71988   ]
 [0.93071467 0.0272762 ]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector and Matrix

In [29]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

# matix is 2D array
matrix = np.array([[1,2,3], 
                   [4,5,6],
                   [7,8,9]])
print("Matrix: \n", matrix)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array properties

In [30]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping

In [32]:
arr = np.arange(12)
print("Original array: ", arr)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
