# Advance operation with business examples

In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [32]:
# Data Structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 260000, 160000, 210000, 150000], # Paradise Biryani
    [2, 270000, 170000, 220000, 120000], # Beijing Bites
    [3, 280000, 180000, 230000, 130000], # Pizza hub
    [4, 140000, 290000, 240000, 190000], # Burger Point
    [5, 250000, 200000, 110000, 300000], # Chai Point
])

print("=== Zomato sales analysis ===")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 restaurant \n", sales_data[0:3])
print("\n Remove the 1st column \n", sales_data[:, 1:])

=== Zomato sales analysis ===

 Sales data shape (5, 5)

 Sample data for 1st 3 restaurant 
 [[     1 260000 160000 210000 150000]
 [     2 270000 170000 220000 120000]
 [     3 280000 180000 230000 130000]]

 Remove the 1st column 
 [[260000 160000 210000 150000]
 [270000 170000 220000 120000]
 [280000 180000 230000 130000]
 [140000 290000 240000 190000]
 [250000 200000 110000 300000]]


In [46]:
# total sales per year
print("Before numbering", np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[:, 1:], axis=0)
print("After numbering", yearly_total)
 
# Minimum sales per year
min_sales = np.min(sales_data[:, 1:], axis=1)
print("MInimum sales ",min_sales)

# Maximum sales per year
max_sales = np.max(sales_data[:, 1:], axis=0)
print("Maximum sales ", max_sales)

# Average sales per restaurant
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("Average sales ", avg_sales)

# Cumulative sales per year
cumsum = np.cumsum(sales_data[:, 1:], axis=1)
print("Cumulative sum " ,cumsum)

Before numbering [     15 1200000 1000000 1010000  890000]
After numbering [1200000 1000000 1010000  890000]
MInimum sales  [150000 120000 130000 140000 110000]
Maximum sales  [280000 290000 240000 300000]
Average sales  [195000. 195000. 205000. 215000. 215000.]
Cumulative sum  [[260000 420000 630000 780000]
 [270000 440000 660000 780000]
 [280000 460000 690000 820000]
 [140000 430000 670000 860000]
 [250000 450000 560000 860000]]


### vectorize()

In [40]:
restaurant_types = np.array(["cafe", "pizza", "buger", "chinese", "veg"])
vectorized_upper = np.vectorize(str.upper) #using vectorize(),you can perform any regular python operation in numpy array
print("Vectorized Upper ", vectorized_upper(restaurant_types))

Vectorized Upper  ['CAFE' 'PIZZA' 'BUGER' 'CHINESE' 'VEG']


In [41]:
monthly_avg = sales_data[:, 1:] /12
print(monthly_avg)

[[21666.66666667 13333.33333333 17500.         12500.        ]
 [22500.         14166.66666667 18333.33333333 10000.        ]
 [23333.33333333 15000.         19166.66666667 10833.33333333]
 [11666.66666667 24166.66666667 20000.         15833.33333333]
 [20833.33333333 16666.66666667  9166.66666667 25000.        ]]
