## Numpy Array Operations

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing", arr[2:7])
print("With step", arr[1:9:2])
print("Negative indexing", arr[-3])

Basic slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [12]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire Row", arr_2d[1])
print("Entire Column", arr_2d[:,1])

Specific element 6
Entire Row [4 5 6]
Entire Column [2 5 8]


# Sorting

In [23]:
unsorted = np.array([1,8,4,7,3,9,2,0,5,6])
print("Sorted Array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [2, 1], [4, 1]])
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0)) #top to bottom sort using axis=0


print("\n Sorted 2D array by row: \n", np.sort(arr_2d_unsorted, axis=1)) #left to righht sort using axis=1

Sorted Array: [0 1 2 3 4 5 6 7 8 9]
Sorted 2D array by column: 
 [[2 1]
 [3 1]
 [4 1]]

 Sorted 2D array by row: 
 [[1 3]
 [1 2]
 [1 4]]


# Filter

In [26]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] #numpy functionality, you can use the expression 1:01:20
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [27]:
mask = numbers > 5
print("Numbers grater than 5", numbers[mask])

Numbers grater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [29]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [32]:
condition_array = np.where(numbers > 5, "True", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and Removing data

In [37]:
# Merging the array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print("Concatenate array: ", combined)

Concatenate array:  [1 2 3 4 5 6]


### Array compatibility

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])

print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", b.shape == c.shape)

Compatibility shapes True
Compatibility shapes False


In [52]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) #vstack(vertical stack) always add the new row.
print(original)
print(with_new_row)

print("---------------------------------------")

new_col = np.array([[5], [8]])
with_new_col = np.hstack((original, new_col)) #hstack(horizontal stack) always add the new column.
print("With new col: \n", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
---------------------------------------
With new col: 
 [[1 2 5]
 [3 4 8]]


### Deletion of Array using index

In [56]:
arr = np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5 6 7]
